name: Build ZMK firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: yukim12143/zmk
          submodules: true

      - name: Fetch config
        uses: actions/checkout@v3
        with:
          repository: yukim12143/zmk-config-Keyball39
          path: config

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install west
        run: pip install west

      - name: Init west
        run: |
          west init -l app
          west update
          west zephyr-export
          pip install -r app/zephyr/scripts/requirements.txt

      - name: Build (Left side)
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=keyball39_left -DZMK_CONFIG=config

      - name: Build (Right side)
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=keyball39_right -DZMK_CONFIG=config -DOUTPUT_DIRECTORY=build/right

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zmk-firmware
          path: |
            build/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
